### ISSUE TITLE
feat(Nx ws * github): init [WiP]

### ISSUE THREAD

**Issue by VladiRR** [VladiRR/svvs#1]
## инициализация
[соглашение по коммитам](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
[сайт эмодзи](https://emojipedia.org/)
- [x] инициализировать Nx ws
[инициализация Nx ws | Nx документация](https://nx.dev/latest/angular/getting-started/getting-started)
`npx create-nx-workspace --preset=angular`
- [x] поменять npm на yarn
- [x] инициализировать github repo
- [x] настроить шаблоны issues

**Comment by Den-dp** [comment]
@VladiRR want to suggest https://www.conventionalcommits.org as a more universal spec for commit message naming (they are heavily based on the Angular Commit Guidelines)
